title: Ivana Drabova
logo: /assets/img/logo.jpg
description: Economist and Computer Scientist | [Email](mailto:ivana.drabova@nyu.edu)| [Linkedin](https://www.linkedin.com/in/ivana-drabova/).

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
