title: Ivana Drabova
logo: /assets/img/logo.jpg
description: Economist and Computer Scientist. [![Gmail Badge](https://img.shields.io/badge/-Email-c14438?style=flat&logo=Gmail&logoColor=white&link=mailto:ivana.drabova@nyu.edu)](mailto:ivana.drabova@nyu.edu)
[![Linkedin Badge](https://img.shields.io/badge/-Linkedin-blue?style=flat&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/ivana-drabova/)](https://www.linkedin.com/in/ivana-drabova/)

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
